# -*- coding: utf-8 -*-
"""HW1 problem6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zp7F5ujmlmsVNJnfR_zinM6dTYJEm2A5
"""

import numpy as np
import matplotlib.pyplot as plt
import random
from math import factorial

rng = np.random.default_rng()
Nsim = 100000
X = rng.random(Nsim)
Y= rng.random(Nsim)
Z= rng.random(Nsim)
bnry = np.zeros(Nsim)
frac_succ = np.zeros(Nsim)

for j in range(Nsim):
  if X[j]**2 + Y[j]**2 < Z[j]:
    if Z[j]**2 > X[j]*Y[j]:
      bnry[j] = 1
    else: bnry[j] = 0
  else: bnry[j] = 0
  frac_succ[j] = np.sum(bnry[:j+1])/(j+1)

plt.figure(1, figsize=(8, 6))
p=np.pi/8-np.pi/192

plt.plot([0, Nsim], [p, p], linewidth=5, label='Analytical Calculation') ## For hypothetical one
plt.plot(np.arange(1, Nsim+1), frac_succ, linewidth=5, label = 'Monte Carlo') #for number of successes
plt.tick_params(labelsize=18)
plt.legend()
plt.xlabel('Number of Runs', fontsize=24)
plt.xscale('log')
plt.ylabel('Probability of Successes', fontsize=24)
plt.title('Probability of Success of the Inequality to Hold vs. Number of Runs ', fontsize=24)
plt.tight_layout()
input

