# -*- coding: utf-8 -*-
"""HW2_problem5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mztBHdRYsrNIIRokYjTmwxPrB8R9UGJV
"""

import numpy as np
import matplotlib.pyplot as plt
import random
from math import factorial

#Part B

rng = np.random.default_rng()

count=0
Z_samples=np.zeros(0)

while count <= 1e5:
  W=rng.random(1)
  Z= 1- W**(1/2)
  Z_samples = np.append(Z_samples, Z)
  count += 1

mean_Z=np.sum(Z_samples)/len(Z_samples)
print(mean_Z)

#Part C

#Starting Position
C = np.ones(1000)
Z = np.zeros(1000)
B= np.zeros(1000)
N = 3

#Each round want to draw 10^3 uniform random, and then do the bernouli and then update C
while N<10**4:
  U=rng.random(1000)
  Z= C/N
  B = (U <= Z).astype(int) #checks if U<Z, if true then 1, if false then 0
  C = C + B
  N += 1

#print(C)
#print(Z)
print("Minimum Core=", min(C))
print("Maximum Core=", max(C))
print("Average Core=", np.average(C))
print("Empirical Mean=", np.average(Z))
print("Empirical Ratio Standard Deviation to Mean=", np.std(Z)/np.average(Z))

plt.figure(1, figsize=(8, 6))
plt.clf()
counts, edges, patches = plt.hist(Z, bins='fd', density=True, label='Normalized Histogram')
num_bins = len(counts)
print("Number of Bins=", num_bins)
bin_widths = np.diff(edges)
print("Bin widths:", bin_widths)

z = np.linspace(0, 1, 200)
h = 2*(1-z)
plt.plot(z, h, 'r-', linewidth=2, label='True h(z)')

plt.grid(True)
plt.legend(fontsize=16)
plt.tick_params(labelsize=18)
plt.title('Density vs. z: A Comparison Between Sampling and the True Density')
plt.xlabel('$z$', fontsize=24)
plt.ylabel('$h(z)$', fontsize=24)
plt.tight_layout()
plt.show()

