# -*- coding: utf-8 -*-
"""HW2_problem1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5DWBYrq_-yFsN1jK3GbpXiDY_YIRImD
"""

import numpy as np
import matplotlib.pyplot as plt
import random
from math import factorial

#Part A
rng = np.random.default_rng()
U=rng.random(1)

if U <= 0.05: Z=1
else:
  if U <= 0.20: Z=2
  else: Z=3

print('U', U)
print('Z', Z)

