# -*- coding: utf-8 -*-
"""HW2_problem3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x6nMS-Tfs0X8d8_1Tkbfbwq4zqeHk5Pd
"""

import numpy as np
import matplotlib.pyplot as plt
import random
from math import factorial

#Part B: Sample Proposal by Inversion
  #sample X~g where g=1/2*e^(-1/2*x)

rng = np.random.default_rng()

count=0
X_samples=np.zeros(0)

while count <= 10:
  W=rng.random(1)
  X= -2*np.log(W)
  X_samples = np.append(X_samples, X)
  count += 1
  #print(X_samples, count)

## Part C: \lambda=1/2, c=4/e
count=0
X_samples=np.zeros(0)

total_count=0
accepted_count = 0
fx_samples=0

while accepted_count < 1e4: ## NEED 10**4
  total_count += 1
  W=rng.random(1)
  X= -2*np.log(W)
  X_samples = np.append(X_samples, X)

  U=rng.random(1)
  if U <= np.e * 1/2 * X* np.e**(-X* 1/2):
    fx_samples = np.append(fx_samples, X)
    accepted_count += 1

#for the mean time between, average the total number of counts divided by the number accepted
mean_time = total_count / accepted_count
print('Mean Time (Number of Skips between Accepts)=', mean_time)

#for emperical acceptance do the fraction of accepted by the fraction of total_count
emperical_acceptance_fraction=accepted_count/total_count
print('Emperical Acceptance Fraction=', emperical_acceptance_fraction)
print('Acceptance Fraction 1/c=', np.e/4)


x = np.linspace(0, 30, 400)
f = x*np.e**(-x)

plt.figure(1, figsize=(8, 6))
plt.clf()
counts, edges, patches = plt.hist(fx_samples, bins='fd', density=True, label='Normalized Histogram')
num_bins = len(counts)
print("Number of Bins=", num_bins)
plt.plot(x, f, 'r-', linewidth=2, label='True f(x)')
print("Number of Bins=", num_bins)
bin_widths = np.diff(edges)
print("Bin widths:", bin_widths)

plt.grid(True)
plt.legend(fontsize=16)
plt.tick_params(labelsize=18)
plt.title('Acceptance-Rejection for c=4/e and Lambda=1/2: f(x) vs. x')
plt.xlabel('$x$', fontsize=24)
plt.ylabel('$f(x)$', fontsize=24)
plt.tight_layout()
plt.show()

## Part C: \lambda=1/5, c=1/(0.16e)
count=0
X_samples=np.zeros(0)

total_count=0
accepted_count = 0
fx_samples=0

while accepted_count < 1e4: ## NEED 10**4
  total_count += 1
  W=rng.random(1)
  X= -5*np.log(W)
  X_samples = np.append(X_samples, X)

  U=rng.random(1)
  if U <= np.e * 0.16 *5 * X* np.e**(X* -4/5):
    fx_samples = np.append(fx_samples, X)
    accepted_count += 1

#for the mean time between, average the total number of counts divided by the number accepted
mean_time = total_count / accepted_count
print('Mean Time (Number of Skips between Accepts)=', mean_time)

#for emperical acceptance do the fraction of accepted by the fraction of total_count
emperical_acceptance_fraction=accepted_count/total_count
print('Emperical Acceptance Fraction=', emperical_acceptance_fraction)
print('Acceptance Fraction 1/c=', (np.e*0.16))


x = np.linspace(0, 30, 400)
f = x*np.e**(-x)

plt.figure(1, figsize=(8, 6))
plt.clf()
counts, edges, patches = plt.hist(fx_samples, bins='fd', density=True, label='Normalized Histogram')
num_bins = len(counts)
print("Number of Bins=", num_bins)
plt.plot(x, f, 'r-', linewidth=2, label='True f(x)')
print("Number of Bins=", num_bins)
bin_widths = np.diff(edges)
print("Bin widths:", bin_widths)

plt.grid(True)
plt.legend(fontsize=16)
plt.tick_params(labelsize=18)
plt.title('Acceptance-Rejection for c=1/(0.16e) and Lambda=1/5: f(x) vs. x')
plt.xlabel('$x$', fontsize=24)
plt.ylabel('$f(x)$', fontsize=24)
plt.tight_layout()
plt.show()

