# -*- coding: utf-8 -*-
"""HW2_problem4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dw012RIaUIEGQlGjhAWqusgJPdrY0fLN
"""

import numpy as np
import matplotlib.pyplot as plt
import random
from math import factorial
from scipy.stats import bernoulli
rng = np.random.default_rng()

N=0
T_values= np.zeros(0)
lambda_f=1000
lambda_s=10
a= 0.9

while N <10**5:
  bernouli = bernoulli.rvs(p=a, size=1)
  #print(bernouli)
  W=rng.random(1)
  if bernouli == 1:
    T_values= np.append(T_values, -(lambda_f)**(-1)*np.log(W))
  else:
    T_values= np.append(T_values,-(lambda_s)**(-1)*np.log(W))
  N+=1

#print(T_values)

print("Number of samples:", len(T_values))
print("Empirical mean:", np.mean(T_values))
count = sum(1 for value in T_values if value > 0.05)
print("Empirical P(T > 50 ms):",count/len(T_values))

plt.figure(1, figsize=(8, 6))
plt.clf()
counts, edges, patches = plt.hist(T_values, bins=300, density=True, label='Normalized Histogram')
num_bins = len(counts)
print("Number of Bins=", num_bins)
bin_widths = np.diff(edges)
print("Bin widths:", bin_widths)

t = np.linspace(0, 1, 200)
f= a*lambda_f*np.exp(-lambda_f * t)+(1-a)*lambda_s*np.exp(-lambda_s * t)
plt.plot(t, f, 'r-', linewidth=2, label='True f(t)')

plt.grid(True)
plt.legend(fontsize=16)
plt.tick_params(labelsize=18)
plt.title('Density vs. t: A Comparison Between Sampling and the True Density')
plt.yscale('log')
plt.xlim(0,1)
plt.xlabel('$t$ (seconds)' , fontsize=24)
plt.ylabel('$f(t)$', fontsize=24)
plt.tight_layout()
plt.show()

