# -*- coding: utf-8 -*-
"""HW3_Problem4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c9LKAbVf_0x_bY2ZrgIZ714euAhX39Ct
"""

import numpy as np
import matplotlib.pyplot as plt
import random
import scipy.special as special
from scipy import stats
import pandas as pd
rng = np.random.default_rng()

#Part B: 1 lion and 2*10^4 Independent Lambs

#Starting Positions
R = 2*10**4
Distance = np.ones(R) * 10
S_1=np.zeros(10**4+1)
S_1[0] = 1
alive = np.ones(R, dtype=bool)

#Loop Over Simulation
for T in range(1,10**4+1):
  U=rng.random(R)

  Distance[alive & (U < 0.25)] -= 2
  Distance[alive & (U>= 0.25)&(U<0.5)]+=2
  Distance[alive & (U>=0.5)]+=0

  alive[Distance == 0] = False
  S_1[T]= np.sum(alive) / R

time=np.arange(0,10**4+1)
timelogprep=np.where(time==0, np.nan, time)
timelog=np.log(timelogprep)

S1logprep= np.where(S_1 == 0, np.nan, S_1)
S1log=np.log(S1logprep)
plt.plot(timelog,S1log,label='Simulation')

slope, intercept, r_value, p_value, std_err = stats.linregress(timelog[100:10001],S1log[100:10001])
beta_1 = -slope
print("Beta_1", beta_1)
print("Slope", slope)

predict=special.erf(10/(2*timelogprep**(1/2)))
predictlogprep= np.where(predict == 0, np.nan, predict)
predictlog=np.log(predictlogprep)
plt.plot(timelog,predictlog,label='Prediction')

plt.legend()
plt.title('log(Sn) vs. log(Steps): Simulation slope of -0.515 and Beta_1 of 0.515 from 10^2 ≤ t ≤ 10^4')
plt.xlabel('log(Steps)')
plt.ylabel('log(Probability Lamb is Alive : Sn)')

#Part C: 2 lions and 2*10^4 Independent Lambs

#Starting Positions
R = 2*10**4
lamb = np.zeros(R, dtype=int)
lion1 = np.ones(R, dtype=int) * 10
lion2 = np.ones(R, dtype=int) * 10
alive = np.ones(R, dtype=bool)
S_2=np.zeros(10**4+1)
S_2[0] = 1

#Loop Over Simulation
for T in range(1,10**4+1):
    # Lamb move
    U_lamb = rng.random(R)
    lamb[U_lamb < 0.5] -= 1
    lamb[U_lamb >= 0.5] += 1

    # Lion 1 move
    U1 = rng.random(R)
    lion1[U1 < 0.5] -= 1
    lion1[U1 >= 0.5] += 1

    # Lion 2 move
    U2 = rng.random(R)
    lion2[U2 < 0.5] -= 1
    lion2[U2 >= 0.5] += 1

    # Capture if either lion with the lamb
    captured = (lion1 == lamb) | (lion2 == lamb)
    alive[captured] = False
    S_2[T] = np.sum(alive) / R

time=np.arange(0,10**4+1)
timelogprep=np.where(time==0, np.nan, time)
timelog=np.log(timelogprep)

S2logprep= np.where(S_2 == 0, np.nan, S_2)
S2log=np.log(S2logprep)

slope, intercept, r_value, p_value, std_err = stats.linregress(timelog[100:10001],S2log[100:10001])
beta_2 = -slope
print("Beta_2", beta_2)
print("Slope", slope)

predict=special.erf(10/(2*timelogprep**(1/2)))
predictlogprep= np.where(predict == 0, np.nan, predict)
predictlog=np.log(predictlogprep)

S1_2=S_1**2
S1_2logprep= np.where(S1_2 == 0, np.nan, S1_2)
S1_2log=np.log(S1_2logprep)

plt.plot(timelog,S1_2log,label='Simulation S1^2')
plt.plot(timelog,S1log,label='Simulation One Lion')
plt.plot(timelog,S2log,label='Simulation Two Lions')
plt.plot(timelog,predictlog,label='Prediction For One Lion')
plt.legend()

plt.legend()
plt.title('log(Sn) vs. log(Steps): For S_2 simulation slope of -0.749 and Beta_1 of 0.749 from 10^2 ≤ t ≤ 10^4')
plt.xlabel('log(Steps)')
plt.ylabel('log(Probability Lamb is Alive : Sn)')

#Tabulating

print("At T=10^2", "S1^2=", S1_2[100], "S_2=", S_2[100])
print("At T=10^3", "S1^2=", S1_2[1000], "S_2=", S_2[1000])
print("At T=10^4", "S1^2=", S1_2[10000], "S_2=", S_2[10000])

