# -*- coding: utf-8 -*-
"""HW3_Problem1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11M_P5MXDURBu83yrKJ-lhUOG6ZL0-spO
"""

import numpy as np

P=[[0.9, 0.1, 0], [0, 0.75, 0.25], [0.5,0,0.5]]
P_50 = np.linalg.matrix_power(P, 50)
print(P_50)

