# -*- coding: utf-8 -*-
"""HW3_Problem2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xr3saPXhDbYs1-JrBq-L8k1JSSlybQ7h
"""

import numpy as np

P=[[1/2,1/2,0,0,0,0], [1/3,0,1/3,0,1/3,0], [0,0,1/4,3/4,0,0],[0,0,1,0,0,0],[0,0,0,0,0,1],[0,0,0,0,1,0]]
P_20 = np.linalg.matrix_power(P, 20)
print("P^20=",P_20)
P_21 = np.linalg.matrix_power(P, 21)
print("P^21=",P_21)

