# -*- coding: utf-8 -*-
"""HW4_Problem4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W8sFuVJaMNgILFv3TQ6nvhGz2sQPnSwg
"""

import numpy as np
rng = np.random.default_rng()

def simulate(start, N):
    time = []
    end = []

    for chain in range(N):
        state = start
        t = 0

        while state not in ["F", "A"]:
            Z = rng.random(1)
            t += 1

            if state == "U":
                if Z < 0.5: state = "M"
                else: state = "I"
            elif state == "I":
                if Z < 0.5: state = "F"
                elif Z < 0.75: state = "A"
                else: state = "U"
            elif state == "M":
                if Z < 0.75: state = "U"
                else: state = "A"

        time.append(t)
        end.append(state)
    return np.array(time), np.array(end)

time_U, end_U = simulate("U", N=10000)
time_M, end_M = simulate("M", N=10000)
time_I, end_I = simulate("I", N=10000)

h_U = np.mean(end_U == "F")
g_U = np.mean(time_U)

tau_U_F = np.mean(time_U[end_U == "F"])
tau_U_A = np.mean(time_U[end_U == "A"])

print(h_U, g_U, tau_U_F, tau_U_A)

h_M = np.mean(end_M == "F")
g_M = np.mean(time_M)

tau_M_F = np.mean(time_M[end_M == "F"])
tau_M_A = np.mean(time_M[end_M == "A"])

print(h_M, g_M, tau_M_F, tau_M_A)

h_I = np.mean(end_I == "F")
g_I = np.mean(time_I)

tau_I_F = np.mean(time_I[end_I == "F"])
tau_I_A = np.mean(time_I[end_I == "A"])

print(h_I, g_I, tau_I_F, tau_I_A)

import matplotlib.pyplot as plt

time= np.arange(1, 31)

Q = np.array([
    [0,    0.5, 0.5],
    [0.25,    0, 0],
    [0.75, 0,   0]
])

R = np.array([
    [0,   0],
    [0.5, 0.25],
    [0,   0.25]
])

PI_A= 3/8
PI_F= 5/8
P_I_F=[]
P_I_A=[]

for t in time:
  matrixmultiply = np.linalg.matrix_power(Q, t-1) @ R
  P_I_F.append(matrixmultiply[1, 0] / PI_F)
  P_I_A.append(matrixmultiply[1, 1] / PI_A)


plt.plot(time, P_I_F, label="Exact Conditional PMF")
plt.hist(time_I[end_I == "F"], density='True', bins=30, label="Simulation Probabilties")
plt.title('Time until Folded State')
plt.xlabel('Time (steps)')
plt.ylabel('Probability of Steps Until Reach Folded')
plt.legend()
plt.show()


plt.plot(time, P_I_A, label="Exact Conditional PMF")
plt.hist(time_I[end_I == "A"],density='True', bins=30, color='red', label="Simulation Probabilties")
plt.title('Time Until Aggregate State')
plt.xlabel('Time (steps)')
plt.ylabel('Probability of Steps Until Reach Aggregated')
plt.legend()
plt.show()

