# -*- coding: utf-8 -*-
"""HW5_Problem3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fAmP27Q4J7Yit5uQUNR0-BEHDDdxszp
"""

import numpy as np
import matplotlib.pyplot as plt
rng = np.random.default_rng()
from scipy import stats

#Part A
P = np.array([
    [0, 1/2, 1/2, 0,0,0,0,0],
    [0,0, 1/2,1/2,0,0,0,0],
    [1/2,0,0,0,1/2,0,0,0],
    [1/3,0,1/3,0,1/3,0,0,0],
    [0,1/3,0,0,0,1/3,1/3,0],
    [0,0,0,0,0,1,0,0],
    [0,0,0,0,0,0,0,1],
    [0,0,0,0,0,0,1,0]
])
q_0=[1/8,1/8,1/8,1/8,1/8,1/8,1/8,1/8]

#For q100:
P_pow_100 = np.linalg.matrix_power(P, 100)
q_P100= q_0 @ P_pow_100
print("q100=", q_P100)

#For q101:
P_pow_101 = np.linalg.matrix_power(P, 101)
q_P101= q_0 @ P_pow_101
print("q101=", q_P101)

#Part B
ones=np.ones((8,8))
d=0.85
q_0=[1/8,1/8,1/8,1/8,1/8,1/8,1/8,1/8]
G=d*P+((1-d)/8)*ones
print("G=",G)
q_n=np.zeros((200, 8))
q_n[0] = q_0
steps=np.arange(1,200)

#Pi from Power Iteration
for n in steps:
  G_pow_n=np.linalg.matrix_power(G, n)
  q_Gn= q_0 @ G_pow_n
  q_n[n]=q_Gn
  difference=q_n[n]-q_n[n-1]
  if np.linalg.norm(difference, ord=1) < 1e-10:
    print("Smallest n:", n)
    print("q_n at Stopping n:", q_n[n])
    break

#Pi from Linear Solver
eigenvalues, eigenvectors = np.linalg.eig(G.T)
indexforval1 = np.where(np.isclose(eigenvalues, 1.0))[0]
target_eigenvector = eigenvectors[:, indexforval1[0]].real
pi = target_eigenvector / np.sum(target_eigenvector)
print("Pi from Linear Solver:", pi)

#Part C

R = 100
T = 10**5
surfer_time = np.zeros((T, R), dtype=int)
surfer_time[0]=[1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,7,7,7,7,7,8,8,8,8,8,8,8,8,8,8,8,8,8,8]

cdf = np.array([
    [0.01875, 0.4625, 0.90625, 0.925, 0.94375, 0.9625, 0.98125, 1.0],
    [0.01875, 0.0375, 0.48125, 0.925, 0.94375, 0.9625, 0.98125, 1.0],
    [0.44375, 0.4625, 0.48125, 0.5, 0.94375, 0.9625, 0.98125, 1.0],
    [0.30208333, 0.32083333, 0.62291667, 0.64166667,
     0.94375, 0.9625, 0.98125, 1.0],
    [0.01875, 0.32083333, 0.33958333, 0.35833333,
     0.37708333, 0.67916667, 0.98125, 1.0],
    [0.01875, 0.0375, 0.05625, 0.075, 0.09375, 0.9625, 0.98125, 1.0],
    [0.01875, 0.0375, 0.05625, 0.075, 0.09375, 0.1125, 0.13125, 1.0],
    [0.01875, 0.0375, 0.05625, 0.075, 0.09375, 0.1125, 0.98125, 1.0]
])

for t in range(1, T):
    previous = surfer_time[t-1, :]
    Z = np.random.rand(R)
    next_state = np.zeros(R)

    if np.any(previous == 1):
        mask = (previous == 1)
        z = Z[mask]
        next_state[mask] = np.where(
            z <= 0.01875, 1,
            np.where(z <= 0.4625, 2,
            np.where(z <= 0.90625, 3,
            np.where(z <= 0.925, 4,
            np.where(z <= 0.94375, 5,
            np.where(z <= 0.9625, 6,
            np.where(z <= 0.98125, 7, 8)))))))
    if np.any(previous == 2):
        mask = (previous == 2)
        z = Z[mask]
        next_state[mask] = np.where(
            z <= 0.01875, 1,
            np.where(z <= 0.0375, 2,
            np.where(z <= 0.48125, 3,
            np.where(z <= 0.925, 4,
            np.where(z <= 0.94375, 5,
            np.where(z <= 0.9625, 6,
            np.where(z <= 0.98125, 7, 8)))))))
    if np.any(previous == 3):
        mask = (previous == 3)
        z = Z[mask]
        next_state[mask] = np.where(
            z <= 0.44375, 1,
            np.where(z <= 0.4625, 2,
            np.where(z <= 0.48125, 3,
            np.where(z <= 0.5, 4,
            np.where(z <= 0.94375, 5,
            np.where(z <= 0.9625, 6,
            np.where(z <= 0.98125, 7, 8)))))))
    if np.any(previous == 4):
        mask = (previous == 4)
        z = Z[mask]
        next_state[mask] = np.where(
            z <= 0.30208333, 1,
            np.where(z <= 0.32083333, 2,
            np.where(z <= 0.62291667, 3,
            np.where(z <= 0.64166667, 4,
            np.where(z <= 0.94375, 5,
            np.where(z <= 0.9625, 6,
            np.where(z <= 0.98125, 7, 8)))))))
    if np.any(previous == 5):
        mask = (previous == 5)
        z = Z[mask]
        next_state[mask] = np.where(
            z <= 0.01875, 1,
            np.where(z <= 0.32083333, 2,
            np.where(z <= 0.33958333, 3,
            np.where(z <= 0.35833333, 4,
            np.where(z <= 0.37708333, 5,
            np.where(z <= 0.67916667, 6,
            np.where(z <= 0.98125, 7, 8)))))))
    if np.any(previous == 6):
        mask = (previous == 6)
        z = Z[mask]
        next_state[mask] = np.where(
            z <= 0.01875, 1,
            np.where(z <= 0.0375, 2,
            np.where(z <= 0.05625, 3,
            np.where(z <= 0.075, 4,
            np.where(z <= 0.09375, 5,
            np.where(z <= 0.9625, 6,
            np.where(z <= 0.98125, 7, 8)))))))
    if np.any(previous == 7):
        mask = (previous == 7)
        z = Z[mask]
        next_state[mask] = np.where(
            z <= 0.01875, 1,
            np.where(z <= 0.0375, 2,
            np.where(z <= 0.05625, 3,
            np.where(z <= 0.075, 4,
            np.where(z <= 0.09375, 5,
            np.where(z <= 0.1125, 6,
            np.where(z <= 0.13125, 7, 8)))))))
    if np.any(previous == 8):
        mask = (previous == 8)
        z = Z[mask]
        next_state[mask] = np.where(
            z <= 0.01875, 1,
            np.where(z <= 0.0375, 2,
            np.where(z <= 0.05625, 3,
            np.where(z <= 0.075, 4,
            np.where(z <= 0.09375, 5,
            np.where(z <= 0.1125, 6,
            np.where(z <= 0.98125, 7, 8)))))))
    surfer_time[t, :] = next_state

#Time averages for Pi

#For Pi average the last 10,000 (well within range previously determined)
total_ones = np.sum(surfer_time[-10000:] == 1)
total_twos = np.sum(surfer_time[-10000:] == 2)
total_threes = np.sum(surfer_time[-10000:] == 3)
total_fours = np.sum(surfer_time[-10000:] == 4)
total_fives = np.sum(surfer_time[-10000:] == 5)
total_sixes = np.sum(surfer_time[-10000:] == 6)
total_sevens = np.sum(surfer_time[-10000:] == 7)
total_eights = np.sum(surfer_time[-10000:] == 8)
sum = total_ones + total_twos + total_threes + total_fours + total_fives + total_sixes + total_sevens + total_eights
pi = [total_ones/sum, total_twos/sum, total_threes/sum, total_fours/sum, total_fives/sum, total_sixes/sum, total_sevens/sum, total_eights/sum]
print(pi)

#For individual surfer
ones= np.sum(surfer_time[-10000:, 0] == 1)
twos = np.sum(surfer_time[-10000:, 0] == 2)
threes = np.sum(surfer_time[-10000:, 0] == 3)
fours = np.sum(surfer_time[-10000:, 0] == 4)
fives = np.sum(surfer_time[-10000:, 0] == 5)
sixes= np.sum(surfer_time[-10000:, 0] == 6)
sevens = np.sum(surfer_time[-10000:, 0] == 7)
eights = np.sum(surfer_time[-10000:, 0] == 8)
sum_onesurfer = ones + twos + threes + fours + fives + sixes + sevens + eights
pi_one_surfer= [ones/sum_onesurfer, twos/sum_onesurfer, threes/sum_onesurfer, fours/sum_onesurfer, fives/sum_onesurfer, sixes/sum_onesurfer, sevens/sum_onesurfer, eights/sum_onesurfer]
print(pi_one_surfer)

#Bar Chart
values=[1,2,3,4,5,6,7,8]
plt.bar(values,pi_one_surfer, label="Pi for One Surfer")
plt.bar(values,pi,alpha=0.7, label= "Pi for All Surfers")
plt.xlabel("States")
plt.ylabel("Probability in Stationary Limit")
plt.title("Stationary Distribution for All Surfers Compared To One Surfer")
plt.legend()
plt.show()

#RMS Calculation
true_pi= [0.07175665, 0.06957763, 0.09250788, 0.04832049, 0.07175665, 0.26054035, 0.19826505, 0.18727529]
checkpoints = np.unique(np.logspace(2, 5, 50).astype(int))
rms = np.zeros(len(checkpoints))

for j, t in enumerate(checkpoints):

    estimates = np.array([
        np.mean(surfer_time[1:t+1, :] == i, axis=0)
        for i in range(1, 9)
    ]).T

    all_errors = np.abs(estimates - true_pi)
    max_error = np.max(all_errors, axis=1)
    rms[j] = np.sqrt(np.mean(max_error**2))

print(checkpoints[-1])
print("True Error at 10^5", rms[-1])
print( "Estimated Error at 10^5", np.sqrt(true_pi[5] * (1 - true_pi[5]) / (10**5)))

log_T = np.log10(checkpoints)
log_rms = np.log10(rms)
states = stats.linregress(log_T, log_rms)
fitted_slope = states.slope
intercept = states.intercept
y = 10**(fitted_slope * log_T + intercept)

plt.loglog(checkpoints, rms, 'o-', label="Calculated RMS")
plt.loglog(checkpoints, y, label=f"Fitted slope = {fitted_slope:.3f}")
plt.xlabel("Time (log scale)")
plt.ylabel("Maximum Root Mean Squared Error")
plt.legend()
plt.title("Maximum Root Mean Squared Error vs. Time")
plt.show()

