# -*- coding: utf-8 -*-
"""HW5_Problem1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pVdd6Mrvh6Xu644wO7C9Ehy9VWU7gJqK
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math

#Part B:

a=1
b=1
q_0=[1,0,0,0,0]
P = np.array([
    [1-a, a, 0, 0, 0],
    [b/4, 1-a*3/4-b*1/4, a*3/4, 0 ,0],
    [0, b*1/2, 1-a*1/2-b*1/2, a*1/2, 0],
    [0, 0, b*3/4, 1-a*1/4-b*3/4, a*1/4],
    [0, 0, 0, b, 1-b]
])

q_n=np.empty((60, 5))
q_2average=np.empty(60)
steps =np.arange(1,60)
for n in steps:
  P_pow_n = np.linalg.matrix_power(P, n)
  q_Pn= q_0 @ P_pow_n
  q_n[n] = q_Pn
  q_2average[n] = np.average(q_n[0:n, 2])
print(q_n)

#For q50:
P_pow_50 = np.linalg.matrix_power(P, 50)
q_P50= q_0 @ P_pow_50
print("q50=", q_P50)

#For q51:
P_pow_51 = np.linalg.matrix_power(P, 51)
q_P51= q_0 @ P_pow_51
print("q51=", q_P51)

#Plotting (using index 2 for k=2 and index 4 for k=4)
plt.plot(steps, q_n[steps, 2], label="k=2")
plt.plot(steps, q_2average[steps], label="k=2 Running Average")
plt.plot(steps, q_n[steps, 4], label="k=4")
plt.xlabel("Step (n)")
plt.ylabel("Probability (qn(k))")
plt.title("Probability vs. Step for Various States")
plt.legend()
plt.show()

#Part C

#Computing with Linear solve
#leaving out [0,0,0,3/40,-1/10] since linearly dependent do not need to solve for all equations
from scipy.linalg import solve
A = np.array([[-3/10,1/40,0,0,0],
              [3/10,-1/4,1/20,0,0],
              [0, 9/40, -4/20, 3/40, 0],
              [0,0, 3/20, -6/40, 1/10],
              [1,1,1,1,1]])
b = np.array([0,0,0,0,1])
x = solve(A, b)
print(x)

#Comparing to binomial
a=0.3
b=0.1
pi_0 = math.comb(4, 0) * (a/(a+b))**0 * (1-a/(a+b))**(4-0)
pi_1 = math.comb(4, 1) * (a/(a+b))**1 * (1-a/(a+b))**(4-1)
pi_2 = math.comb(4, 2) * (a/(a+b))**2 * (1-a/(a+b))**(4-2)
pi_3 = math.comb(4, 3) * (a/(a+b))**3 * (1-a/(a+b))**(4-3)
pi_4 = math.comb(4, 4) * (a/(a+b))**4 * (1-a/(a+b))**(4-4)
print("pi_0=", pi_0)
print("pi_1=", pi_1)
print("pi_2=", pi_2)
print("pi_3=", pi_3)
print("pi_4=", pi_4)

#Plotting Linear Solver Pi
labels=[0,1,2,3,4]
plt.bar(labels, x)
plt.xlabel("State (k)")
plt.ylabel("Stationary Probability (pi_k)")
plt.title("Stationary Probability vs. State (k)")

#Part C:

#Comparing Computed Pi to q_n
a=0.3
b=0.1
q_0=[1,0,0,0,0]
P = np.array([
    [1-a, a, 0, 0, 0],
    [b/4, 1-a*3/4-b*1/4, a*3/4, 0 ,0],
    [0, b*1/2, 1-a*1/2-b*1/2, a*1/2, 0],
    [0, 0, b*3/4, 1-a*1/4-b*3/4, a*1/4],
    [0, 0, 0, b, 1-b]
])

q_n=np.empty((60, 5))
q_2average=np.empty(60)
steps =np.arange(1,60)
for n in steps:
  P_pow_n = np.linalg.matrix_power(P, n)
  q_Pn= q_0 @ P_pow_n
  q_n[n] = q_Pn


#Plotting
plt.plot(steps, q_n[steps, 0], label="k=0")
plt.plot(steps, np.full((59, 1), 0.00390625), linestyle =":", label="Pi k=0")
plt.plot(steps, q_n[steps, 1], label="k=1")
plt.plot(steps, np.full((59, 1), 0.046875), linestyle =":", label="Pi k=1")
plt.plot(steps, q_n[steps, 2], label="k=2")
plt.plot(steps, np.full((59, 1), 0.2109375 ), linestyle =":", label="Pi k=2")
plt.plot(steps, q_n[steps, 3], label="k=3")
plt.plot(steps, np.full((59, 1), 0.421875), linestyle =":", label="Pi k=3")
plt.plot(steps, q_n[steps, 4], label="k=4")
plt.plot(steps, np.full((59, 1), 0.31640625), linestyle =":", label="Pi k=4")
plt.xlabel("Step (n)")
plt.ylabel("Probability (qn(k))")
plt.title("Probability vs. Step for Various States")
plt.legend()
plt.show()

#Finding the smallest n where the difference satisfied
steps_long = np.arange(1, 200)
max_difference = np.empty(199)
pi = x
q_n = np.zeros((200, 5))
q_n[0] = q_0

for n in steps_long:
    P_pow_n = np.linalg.matrix_power(P, n)
    q_Pn = q_0 @ P_pow_n
    q_n[n] = q_Pn

for n in steps_long:
    difference_0 = np.abs(q_n[n, 0] - pi[0])
    difference_1 = np.abs(q_n[n, 1] - pi[1])
    difference_2 = np.abs(q_n[n, 2] - pi[2])
    difference_3 = np.abs(q_n[n, 3] - pi[3])
    difference_4 = np.abs(q_n[n, 4] - pi[4])
    max_difference[n-1] = np.max([difference_0, difference_1, difference_2, difference_3, difference_4])
    if max_difference[n-1] < 1e-6:
        print("Smallest n:", n)
        break

#Finding SLEM
eigenvalues = np.linalg.eigvals(P)
eigenvalue_modulus = np.abs(eigenvalues)
eigenvalue_modulus_sorted = np.sort(eigenvalue_modulus)[::-1]
SLEM = eigenvalue_modulus_sorted[1]

print("Eigenvalues:", eigenvalues)
print("Eigenvalue moduli:", eigenvalue_modulus)
print("SLEM:", SLEM)

