# -*- coding: utf-8 -*-
"""HW6_Problem 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HY-4kHbTk90p74e5iHYeyTdf6leVG1Bu
"""

import math
import numpy as np
import matplotlib.pyplot as plt

#Part C

R_values = np.linspace(0.5, 3, 200)

for N in [100, 1000]:
    K = N // 10
    h1_values = []
    for R in R_values:
      rhosum=0
      for j in range (0, K):
        rhoj = 1
        for k in range(1, j + 1):
          rhoj *= N / (R * (N - k))
        rhosum+=rhoj
      h1 = 1 / rhosum
      h1_values.append(h1)

    plt.plot(R_values, h1_values, label=f'Exact h1, N={N}')

y=1-R_values**(-1)
plt.plot(R_values,y,label="1-1/R0")
plt.legend()
plt.xlabel("R0")
plt.ylabel("Probability of reaching K before 0 from 1 Infected")
plt.title("Outbreak Probability vs. R0")
plt.show()

# Part D

e0 = 0
e10 = 0
gamma = 1
R = [0.5, 0.8, 1.5, 3]
N = 100
deltat = 0.005

for R0 in R:
    p = lambda x: R0*gamma*x*(N-x)*deltat / N
    q = lambda x: gamma*x*deltat

    E = np.array([
        [p(1)+q(1), -p(1), 0, 0, 0, 0, 0, 0, 0],
        [-q(2), p(2)+q(2), -p(2), 0, 0, 0, 0, 0, 0],
        [0, -q(3), p(3)+q(3), -p(3), 0, 0, 0, 0, 0],
        [0, 0, -q(4), p(4)+q(4), -p(4), 0, 0, 0, 0],
        [0, 0, 0, -q(5), p(5)+q(5), -p(5), 0, 0, 0],
        [0, 0, 0, 0, -q(6), p(6)+q(6), -p(6), 0, 0],
        [0, 0, 0, 0, 0, -q(7), p(7)+q(7), -p(7), 0],
        [0, 0, 0, 0, 0, 0, -q(8), p(8)+q(8), -p(8)],
        [0, 0, 0, 0, 0, 0, 0, -q(9), p(9)+q(9)]
    ])

    b = np.ones(9)
    e = np.linalg.solve(E, b)

    print(f"R0 = {R0}, e1*deltat = {e[0]*deltat:.4f}")

# Check R0 = 1.5 by simulation

R0 = 1.5
p = lambda x: R0*gamma*x*(N-x)*deltat / N
q = lambda x: gamma*x*deltat

num_simulations = 100000
times = []

for sim in range(num_simulations):
    x = 1
    steps = 0

    while x != 0 and x != 10:
        r = np.random.random()

        if r < p(x):
            x += 1
        elif r < p(x) + q(x):
            x -= 1
        # Otherwise, x stays the same

        steps += 1

    times.append(steps * deltat)

print("Simulated mean time:", np.mean(times))