# -*- coding: utf-8 -*-
"""HW6_Problem1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o6zVoNql4mex7MJ8D6T4LCv7ap4k4CRE
"""

import numpy as np

m=[3,4,5,6,7,8,9,10,11,12]

for i in m:
  P= np.zeros((i,i))
  for j in range (i-1):
    P[j, j + 1] = 1
  P[i - 1, 0] = 0.5
  P[i - 1, 1] = 0.5

  B = np.eye(i, dtype=bool)

  M = 0
  while not B.all():
      B = (B @ (P > 0)) > 0
      M += 1

  eigenvalues = np.linalg.eigvals(P)
  eigenvalue_modulus = np.abs(eigenvalues)
  eigenvalue_modulus_sorted = np.sort(eigenvalue_modulus)[::-1]
  SLEM = eigenvalue_modulus_sorted[1]

  bound = (i - 1)**2 + 1
  print(i, M, bound, SLEM)

